### ISSUE TITLE
Application hangs when given a long expression.

### ISSUE THREAD

**Issue by DefaulT47** [arch10/Calculator-Plus#28]
**Describe the bug**
If I write a long expression and press equal to and return to this application after a while, it gets hanged !!!!!! 

**To Reproduce**
1. OPEN CALCULATOR PLUS. 

2. Write down a long expression and press equal to button.

3. Press the multi tasking button and then come back to the application little while later.

4. The application hangs

**Expected behavior**
The expected behaviour should have been that, it should have given me the answer instead of hanging itself 😑

**Screenshots**
N/A

**Android (please complete the following information):**
 - Device: Realme 6 (RMX 2001). 
 - OS: Android 10
 - App Version 1.11.1

**Comment by arch10** [comment]
Fixed in latest beta
2.0.0
