### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by DefaulT47** [arch10/Calculator-Plus#40]
Please make a a feature in which I will be able to share my history results .

1. Go to 'History' from the three dot menu
2. Press and hold on the any result
3. There should be an option to share that particular history 

**Android (please complete the following information):**
 - Device: Realme 6
 - OS: Realme UI 2.0
 - App Version 2.1.0

**Additional context**

**Comment by arch10** [comment]
Added to latest beta 2.1.2
